import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { cn } from '@/lib/utils';
import './globals.css';

const nourdBold = localFont({
  src: '../assets/fonts/nourd.woff2',
  variable: '--font-nourd',
  display: 'swap',
});

const glacialRegular = localFont({
  src: '../assets/fonts/glacial.woff2',
  variable: '--font-glacial',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={cn('antialiased', nourdBold.variable, glacialRegular.variable)}>
        {children}
      </body>
    </html>
  );
}
